# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1ced636f0dc77e5db9ca6928c9178c32a78d6340001d4a52510d66e2f48c6f8df547b2ed2da8de017d00ce25cdd04ddd7869d18d0a4202e8838c2ba050a6ef3

test:
  secret_key_base: 449435c45141a635abb354daa408908f207b079585cf1a85e8a44d10c8ad5f8d088e739c03d38bc8c8ebaba2f32c3086a6cd143bad65de75aabe2b48952d5119

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
